### ISSUE TITLE
Update dependencies for fonttools 4.x

### ISSUE THREAD

**Issue by benkiel** [daltonmaag/statmake#10]
Currently, pip will complain if you try to install statmake in an environment that has fontTools 4.x installed. I quickly looked for a reference for how version numbers are being specified in the `.toml` file but couldn't find anything (likely missing it, I know, I'm not familiar with this syntax); otherwise this would be a PR.

**Comment by madig** [comment]
Derp. Just noticed this as well. Poetry recommends specifying minimum versions like so: "^3.38", which translates to ">= 3.38, < 4.0". Good for control, but also annoying in some cases. Just changed this to ">= 3.38". Maybe I'll go with "^3.38 | ^4.0" in the future, let's see.

**Comment by madig** [comment]
https://github.com/daltonmaag/statmake/releases/tag/v0.1.4

**Comment by benkiel** [comment]
Got it. Poetry docs leave a bit to be desired.... Thanks for fixing!
