### ISSUE TITLE
designspace distribution changes along axes

### ISSUE THREAD

**Issue by weiweihuanghuang** [daltonmaag/statmake#19]
I have a weight, wdith designspace where the instances' weight values at the Condensed end differ to the Expanded end, just for example:

Condensed (100):
Light: 120
Regular: 450
Bold: 800

Normal (500):
Light: 100
Regular: 400
Bold: 900

Expanded (1000):
Light: 90
Regular: 350
Bold: 900

I don't understand how the STAT table works fully but do I need to do something differently for defining the style space?

**Comment by weiweihuanghuang** [comment]
So far I just used only

**Comment by madig** [comment]
You are skewing the Designspace, this won't work as you'd expect it to. Keep the Designspace rectangular. All your weight values _must stay the same_ no matter what width you have: Light is always 300, Regular always 400, Bold always 700. Mind you that in a VF, all axes change independently from one another, which is why there is no way for a STAT table to have different names depending on axis state.

**Comment by weiweihuanghuang** [comment]
I should've been more clear, the actual designspace itself is rectangular, it's the instances that are like such.

**Comment by madig** [comment]
I don't think that will work either.

**Comment by weiweihuanghuang** [comment]
Is there any solution? I'm converting an old project into a variable font and I can't change the instances.

**Comment by twardoch** [comment]
You’re giving design locations, but in a spec-compliant VF you should have usWeightClass-compatible weights and usWidthClass-Compatible widths. That means that you'd need to counter-skew your designspace (extrapolate some masters) so that the STAT axis instances and the fvar instance matrix become regularized. There is currently no other way :/ and there are no tools that would do this automatically, I believe.

**Comment by twardoch** [comment]
If you have breaks in your designspace, the really best way is to make intermediate masters. This is relatively easily done: just export all your instances as UFOs and use them to build a new regularized designspace. The VF will be larger of course, but that'd be the quick & easy way.

**Comment by weiweihuanghuang** [comment]
Thanks @twardoch, what do you mean by breaks?
If it helps, to illustrate, this is the designspace:

![Uploading Screen Shot 2020-01-13 at 9.54.08 pm.png…]()

Surely many superfamilies do not share the same weight across widths....

**Comment by twardoch** [comment]
Yes, that is what I mean by breaks. In some designs, you have a uniformly distorted space, made as if you just dragged in or out one corner of a grid. Then you just need to reinterpolate the corner. 

You can have any design designspace you want. But that's not necessarily what needs to go into the font. The VF has a "production designspace", and the current tech kind of requires that it's all orthogonal. The avar table can skew the mapping a bit, but does it uniformly per axis. 

So you need to perform a projection of the design designspace to the production designspace. It's not hard, just identify all the places that are non-linear breaks, export them as instances and make a new .designspace that uses these instances as masters in an orthogonal production designspace.

**Comment by twardoch** [comment]
Superfamilies can have whatever they want :) The point is that not alldesignspaces can be expressed in the current VF format without extra data. But you can always add extra data (masters) and then you'll have an orthogonal designspace. 

There should be tools that do that automatically, but these tools don't exist yet.

**Comment by twardoch** [comment]
The distortions in this designspace are quite “ambitious” to the extent that I think pretty much all instances would need to become masters. This will increase the file size, but is actually trivial to make – as I said, just export your instances as UFOs, then make a new .designspace that places them all at orthogonal coordinates that use orthogonal, standardized locations for wght & wdth. And use that with fontmake.

**Comment by weiweihuanghuang** [comment]
Thank you again for your clear explanation. I understand the problem and solution now...

**Comment by twardoch** [comment]
It would be possible to “optimize away” a few out of these "instances as masters", but not many in this setup. But let's say you only have the complex skewing in the left 25% of the image, and the right 75% is fully orthogonal in your design. Then you'd only need those "moved" intermediate masters for the left 25%. 

And if, as it often happens, the distortion would be such that the one corner is moved in but the rest of the grid is distorted proportionally, then you wouldn't need that at all. Say in the wides (wd 120) your black is at master wt 900 and in the narrows (wd 80) the black is at instance wt 800. 

Then in the VF production designspace you'd either give up the small triangle, export the wd 80 wt 800 instance and just use that as wd 80 wt 900 master, or you extrapolate a wd 120 wt 1000 or whatever instance and use that as wd 120 wt 900.

**Comment by twardoch** [comment]
Overall, this topic is somewhat similar to cartographic map projections, and your case is a bit like cartograms: https://en.wikipedia.org/wiki/Cartogram

I can imagine that some of the maths used in cartographic map projections could be used in the design>production designspace “normalization” process, if it were to be automated.

**Comment by twardoch** [comment]
This is another case that a tool mentioned in https://github.com/googlefonts/fontmake/issues/609 should be tasked with
