### ISSUE TITLE
Option to include more STAT entries than there are fvar entries

### ISSUE THREAD

**Issue by madig** [daltonmaag/statmake#22]
If you want to keep the font menu manageable but provide names for _everything_.

**Comment by twardoch** [comment]
Oh, is that not possible now?

**Comment by madig** [comment]
statmake currently subsets the Stylespace to fit the fvar.

**Comment by arialcrime** [comment]
Oh yes, that would be really nice. I am currently running into [that very problem](https://github.com/undercasetype/Fraunces/issues/200).

**Comment by madig** [comment]
I am going to close this issue until I actually need to solve it.

If you need this, consider using fontTools' builder instead, which lets you generate whatever STAT table you want.
