### ISSUE TITLE
Replace _default_name_string with table__n_a_m_e.getDebugName

### ISSUE THREAD

**Issue by madig** [daltonmaag/statmake#6]
https://github.com/fonttools/fonttools/blob/683547dde2ab2d7b805c6b0164deb15f95b7dc2f/Lib/fontTools/ttLib/tables/_n_a_m_e.py#L105-L124

**Comment by davelab6** [comment]
Any updates on this?

**Comment by madig** [comment]
Had no time for further work, but this is a change that should have no user-visible chnage. One day.

**Comment by madig** [comment]
Fixed in master.
